Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0

In [156]:
import pandas as pd
data =pd.read_csv('ratings.csv')
films =data.query('rating =={}'.format(5.0))
films['movieId'].value_counts().head(1)

318    153
Name: movieId, dtype: int64

Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity

In [91]:
power = pd.read_csv('power.csv')
filtered_countries_1 = power [((power['country']=='Latvia') | (power['country']=='Lithuania') | (power['country']=='Estonia')) ]
filtered_countries_2 = filtered_countries_1[((filtered_countries_1['quantity'] > 0) & (filtered_countries_1['year'] >= 2005)
                                            & (filtered_countries_1['year'] <= 2010) &((filtered_countries_1['category'] ==4)
                                            | (filtered_countries_1['category'] ==12) | (filtered_countries_1['category'] ==21)))]
sum(filtered_countries_2['quantity'])

240580.0

Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [102]:
pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')[1]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1001836,-,1008480,"-0,66 %",-06644,16:25:00
1,NaN,EUR/RUB,910645,-,918475,"-0,85 %",-07830,16:24:00
2,NaN,USD/RUB,775490,-,780645,"-0,66 %",-05155,16:24:00
3,NaN,JPY/RUB,07319,-,07367,"-0,66 %",-00049,16:25:00
4,NaN,CNY/RUB,114202,-,114966,"-0,66 %",-00764,16:24:00
5,NaN,CHF/RUB,843470,-,851525,"-0,95 %",-08055,16:24:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11743,-,11766,"-0,19 %",-00023,16:24:00
8,NaN,EUR/GBP,09089,-,09109,"-0,22 %",-00020,16:24:00
9,NaN,EUR/JPY,1244150,-,1246700,"-0,20 %",-02550,16:24:00
10,NaN,EUR/CHF,10796,-,10789,"0,06 %",00007,16:24:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08516,-,08499,"0,20 %",00017,16:25:00
13,NaN,USD/GBP,07739,-,07741,"-0,02 %",-00002,16:24:00
14,NaN,USD/JPY,1059555,-,1059770,"-0,02 %",-00215,16:24:00
15,NaN,USD/CHF,09193,-,09170,"0,25 %",00023,16:24:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08000,-,08000,"0,19 %",00000,16:24:00
18,NaN,JPY/GBP,00073,-,00073,"0,00 %",00000,16:25:00
19,NaN,JPY/USD,00094,-,00094,"0,01 %",00000,16:24:00
20,NaN,JPY/CHF (100:1),08700,-,08700,"0,28 %",00000,16:24:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,12922,-,12916,"0,04 %",00006,16:24:00
23,NaN,GBP/JPY,1368846,-,1368843,"0,00 %",00003,16:25:00
24,NaN,GBP/EUR,11002,-,10980,"0,20 %",00022,16:24:00
25,NaN,GBP/CHF,11879,-,11845,"0,28 %",00034,16:24:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,11879,-,11845,"0,28 %",00034,16:24:00
28,NaN,EUR/CHF,10796,-,10789,"0,06 %",00007,16:24:00
29,NaN,JPY/CHF (100:1),08700,-,08700,"0,28 %",00000,16:24:00
30,NaN,USD/CHF,09193,-,09170,"0,25 %",00023,16:24:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,331491,-,333258,"-0,53 %",-01767,16:25:00
33,NaN,USD/UAH,282300,-,283250,"-0,34 %",-00950,16:23:00
34,NaN,CHF/UAH,307048,-,308955,"-0,62 %",-01907,16:24:00
35,NaN,GBP/UAH,364703,-,365902,"-0,33 %",-01199,16:25:00

Задание 4
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [203]:
data =pd.read_csv('ratings.csv')
data_low = data.loc[data['rating'] <=2].copy()
data_low['class'] = 'низкий'
data_av = data.loc[(data['rating']>2)& (data['rating'] <=4)].copy()
data_av['class'] = 'средний'
data_high = data.loc[(data['rating']==4.5) | (data['rating']==5)].copy()
data_high['class'] = 'высокий'
new_df = pd.concat([data_low, data_av,data_high], ignore_index = True)
new_df

        userId  movieId  rating   timestamp    class
0            1     1219     2.0   964983393   низкий
1            1     2253     2.0   964981775   низкий
2            1     2338     2.0   964983546   низкий
3            1     2389     2.0   964983094   низкий
4            1     2617     2.0   964982588   низкий
...        ...      ...     ...         ...      ...
100831     610   160527     4.5  1479544998  высокий
100832     610   164179     5.0  1493845631  высокий
100833     610   168248     5.0  1493850091  высокий
100834     610   168250     5.0  1494273047  высокий
100835     610   168252     5.0  1493846352  высокий

[100836 rows x 5 columns]

Задание 6
Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [321]:
year =list(range(1950, 2011))
data =pd.read_csv('movies.csv')
data['year'] = 1
def production_year(st):
    for j in year:
        if str(j) in st:
            return j
    return 1900
for i in range(len(data)):
    y = production_year(data.loc[i]['title'])
    data['year'].loc[i]=y
data1 =pd.read_csv('ratings.csv') 
data1 = data1.groupby('movieId').mean()['rating']
data=data.set_index('movieId').join(data1)
data.groupby('year').mean().sort_values('rating',ascending = False)

C:\Users\skinn\anaconda3\lib\site-packages\pandas\core\indexing.py:671: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

        rating
year
1971  3.811243
1957  3.767680
1951  3.718044
1952  3.700104
1955  3.672863
...        ...
1992  3.082417
1988  3.067250
1989  3.045879
1987  3.041854
1991  3.030564

[62 rows x 1 columns]